### ISSUE TITLE
Class 'Epsilon_Page_Generator' not found

### ISSUE THREAD

**Issue by mvpopuk** [ColorlibHQ/unapp#37]
So I choose a page as my front page and "blog" for blog and I get this error:

Fatal error: Uncaught Error: Class 'Epsilon_Page_Generator' not found in 
\wp-content\themes\unapp-master\front-page.php:55 

Stack trace: 

```
#0 \wp-includes\template-loader.php(98): include() 
#1 \wp-blog-header.php(19): require_once('C:\\xampp\\htdocs...') 
#2 \index.php(17): require('C:\\xampp\\htdocs...') 
#3 {main} thrown in \wp-content\themes\unapp-master\front-page.php on line 55
```

Any toughts ?
Thanks.

**Comment by cristianraiber** [comment]
You need to learn to clone GitHub repository with github submodules. If you use Git CLI, use this:

`git clone --recursive {repo_url}`
